//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShitSGK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class films
    {
        public int Id_films { get; set; }
        public string name { get; set; }
        public int duration { get; set; }
        public System.DateTime start_of_rental { get; set; }
        public System.DateTime end_of_rental { get; set; }
        public string rental_company { get; set; }
    }
}
