//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShitSGK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class places
    {
        public int Id_places { get; set; }
        public int Id_Hall { get; set; }
        public int row { get; set; }
        public int place { get; set; }
    }
}
