//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShitSGK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Код_товара { get; set; }
        public string Название { get; set; }
        public float Цена { get; set; }
        public string Единица_измерения { get; set; }
    }
}
