//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShitSGK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Код_товара { get; set; }
        public int Код_клиента { get; set; }
        public System.DateTime Дата_продажи { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int Количество { get; set; }
        public int Код_продажи { get; set; }
    }
}
