//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShitSGK.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessions
    {
        public int Id_sessions { get; set; }
        public int Id_Hall { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan time { get; set; }
        public string film { get; set; }
    
        public virtual Halls Halls { get; set; }
    }
}
